Now closes the bot session, should prevent error
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error getting updates: [409] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

Spring auto reload is slowed massively by this change. But as of now, this is irrelevant.